# Generated by Django 5.2.4 on 2025-11-11 18:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='ai_insights',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='anomaly_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receipt',
            name='auto_categorized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receipt',
            name='auto_transaction_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receipt',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='receipt',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='duplicate_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receipt',
            name='language',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='linked_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.transaction'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='validation_status',
            field=models.CharField(choices=[('pending', 'Pending Validation'), ('valid', 'Valid'), ('needs_review', 'Needs Review'), ('invalid', 'Invalid')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('anomaly_id', models.AutoField(primary_key=True, serialize=False)),
                ('anomaly_type', models.CharField(choices=[('unusual_amount', 'Unusual Amount'), ('duplicate_charge', 'Duplicate Charge'), ('unusual_vendor', 'Unusual Vendor'), ('unusual_category', 'Unusual Category'), ('unusual_time', 'Unusual Time'), ('budget_exceeded', 'Budget Exceeded')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('description', models.TextField()),
                ('confidence_score', models.FloatField(default=0.0)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.receipt')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anomaly',
                'verbose_name_plural': 'Anomalies',
                'db_table': 'Anomalies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('forecast_id', models.AutoField(primary_key=True, serialize=False)),
                ('forecast_type', models.CharField(choices=[('expense', 'Expense Forecast'), ('income', 'Income Forecast'), ('cashflow', 'Cash Flow Forecast'), ('budget', 'Budget Forecast')], max_length=50)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('predicted_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('factors', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Forecast',
                'verbose_name_plural': 'Forecasts',
                'db_table': 'Forecasts',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('reminder_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('reminder_type', models.CharField(choices=[('bill_payment', 'Bill Payment'), ('recurring_expense', 'Recurring Expense'), ('budget_alert', 'Budget Alert'), ('seasonal', 'Seasonal Reminder')], max_length=50)),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vendor', models.CharField(blank=True, max_length=100, null=True)),
                ('recurring', models.BooleanField(default=False)),
                ('recurring_frequency', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reminder',
                'verbose_name_plural': 'Reminders',
                'db_table': 'Reminders',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='DuplicateReceipt',
            fields=[
                ('duplicate_id', models.AutoField(primary_key=True, serialize=False)),
                ('similarity_score', models.FloatField(default=0.0)),
                ('merged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('duplicate_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_duplicates', to='api.receipt')),
                ('original_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicates', to='api.receipt')),
            ],
            options={
                'verbose_name': 'Duplicate Receipt',
                'verbose_name_plural': 'Duplicate Receipts',
                'db_table': 'DuplicateReceipts',
                'unique_together': {('original_receipt', 'duplicate_receipt')},
            },
        ),
    ]
