# Generated by Django 5.2.4 on 2025-11-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_receipt_ai_insights_receipt_anomaly_checked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='linked_transaction',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='user',
        ),
        migrations.RemoveField(
            model_name='anomaly',
            name='receipt',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.DeleteModel(
            name='DuplicateReceipt',
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
